removed roles and apply button, added cow.
HackDavis/hackdavis.github.io pull request #23
Opened 2018-05-01 10:07 UTC by eliotwinchell

2018-05-01 19:15 UTC, klanmiko requested changes
See build system in README for more details. Otherwise the website itself looks good

2018-05-01 19:15 UTC, klanmiko commented on index.html
> +    <title>HackDavis | January 2019</title>
Please see the updated README on how to deploy this website. Make these changes on recruitment.html and then use the scripts to render the website onto this, or you could just copy over these changes to that file manually.

2018-05-01 19:15 UTC, klanmiko commented on scripts/initial_map.json
>  {
This file does not have to be changed, I think you ran scripts/compile_current.js

2018-05-01 19:15 UTC, klanmiko commented on package.json
> +    "react": "^16.3.2",
Also why have these packages been added?

2018-05-02 04:13 UTC, klanmiko requested changes
Still need to modify recruitment.html manually to update the template

2018-05-02 17:16 UTC, thebearjew commented
Moo

2018-05-02 21:31 UTC, klanmiko approved these changes

2018-05-02 21:31 UTC, merged